apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calc-api-system

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - hpa.yaml

images:
  - name: calc-api
    newName: calc-api
    newTag: v1.0.0